name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run apt update
      run: sudo apt update
    - name: Install general dependencies
      run: sudo apt install -y autoconf pkgconf cmake clang build-essential
    - name: Install LibELF for AF_XDP/LibBPF
      run: sudo apt install -y libelf-dev 
    - name: Build Common JSON-C
      run: make -C modules/common jsonc
    - name: Install Common JSON-C
      run: sudo make -C modules/common jsonc_install
    - name: Build Common Main
      run: make -C modules/common
    - name: Install Common
      run: sudo make -C modules/common install
    - name: Build LibBPF
      run: make libbpf
    - name: Build main
      run: make
    - name: Install main
      run: sudo make install
    - name: Store build artifacts
      uses: actions/upload-artifact@master
      with:
        name: build-output
        path: build/pcktbatch
