name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run apt update
      run: sudo apt update
    - name: Install LibYAML dependencies
      run: sudo apt install -y autoconf libtool
    - name: Install LibELF for AF_XDP/LibBPF
      run: sudo apt install -y libelf-dev 
    - name: Make project
      run: sudo make
    - name: Install project
      run: sudo make install
    - name: Store build artifacts
      uses: actions/upload-artifact@master
      with:
        name: build-output
        path: build/pcktbatch
